name: vprofile actions

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-2
  ECR_REPOSITORY: vprofileapp
  EKS_CLUSTER: vprofile-eks

jobs:
  BUILD_AND_PUBLISH:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build & Upload image to ECR
        uses: appleboy/docker-ecr-action@v0.20.0   # pin a release
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region:     ${{ env.AWS_REGION }}
          registry:   ${{ secrets.REGISTRY }}             # e.g. 123456789012.dkr.ecr.us-east-2.amazonaws.com
          repo:       ${{ env.ECR_REPOSITORY }}           # e.g. vprofileapp
          tags:       latest,${{ github.run_number }},${{ github.sha }}
          dockerfile: ./Dockerfile
          context:    ./
          daemon_off: false
